### PR TITLE
Update ntex-mqtt

### PR DESCRIPTION
**Pull request by evshary**

### CODE REVIEW

**Comment by gabrik** [comment]
I want to check this before it gets merged

**Comment by evshary** [comment]
> I want to check this before it gets merged

That would be great. I've only tested manually in the bridge mode.

**Comment by gabrik** [comment]
Just wondering if we can take advantage of this PR to address: https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/issues/27

**Comment by evshary** [comment]
I'm not sure. They removed the websocket server example from this commit.
https://github.com/ntex-rs/ntex-mqtt/pull/167
I'll ask them.

**Review by gabrik — APPROVED** [review]
LGTM

**Comment by evshary** [comment]
I'll follow the MQTT-WS issue, but it might not be in this PR.
My ideal roadmap for MQTT:

* Add system tests in the plugins
* Able to test in zenoh-tests
* Support MQTT-WS (including tests)

**Pull request merged**
